from typing_extensions import final
from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 289)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(290, 257, 101, 20))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setPixmap(QtGui.QPixmap("sysFiles/zrn_logo_no_back_fit.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 381, 21))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 60, 381, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 171, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 171, 17))
        self.label_4.setObjectName("label_4")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 110, 381, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 186, 131, 21))
        self.label_5.setObjectName("label_5")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(90, 180, 51, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 220, 131, 31))
        self.label_6.setObjectName("label_6")
        self.textEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_4.setGeometry(QtCore.QRect(140, 220, 51, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(230, 180, 41, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(280, 180, 41, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(330, 180, 41, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 150, 181, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(230, 150, 161, 20))
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(192, 150, 31, 101))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(10, 165, 381, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(10, 25, 381, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(280, 230, 131, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(270, 240, 20, 61))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 262, 261, 21))
        self.pushButton.setObjectName("pushButton")
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setGeometry(QtCore.QRect(0, 250, 281, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.pushButton.clicked.connect(self.readAndFeed)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def readAndFeed(self):
        inputXYZ1 = self.textEdit.toPlainText().split(",")
        inputXYZ2 = self.textEdit_2.toPlainText().split(",")
        initTime = self.textEdit_3.toPlainText()
        updateSpeed = self.textEdit_4.toPlainText()
        if self.checkBox.isChecked() == True:
            coordinateValue1 = 0
        if self.checkBox_2.isChecked() == True:
            coordinateValue2 = 1
        if self.checkBox_3.isChecked() == True:
            coordinateValue2 = 2
        try:
            finalComm1 = "python sysFiles/lorenz1.py "+ str(updateSpeed) + " " + str(inputXYZ1[0]) +" "+str(inputXYZ1[1]) + " " + str(inputXYZ1[2]) + " "+ str(coordinateValue1) +" "+ str(coordinateValue2) + " 1 &"
            finalComm2 = "python sysFiles/lorenz1.py "+ str(updateSpeed) + " " + str(inputXYZ2[0]) +" "+str(inputXYZ2[1]) + " " + str(inputXYZ2[2]) +" " + str(coordinateValue1) +" "+ str(coordinateValue2) + " 2 &"
            print(finalComm1)
            os.system(finalComm1)
            os.system(finalComm2)
        except:
            print("Failed !, Complete All the values")
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Lorenz Attractor Simulation"))
        self.label_2.setText(_translate("Dialog", "Initial Values For x,y,z"))
        self.label_3.setText(_translate("Dialog", "Instance 1"))
        self.label_4.setText(_translate("Dialog", "Instance 2"))
        self.label_5.setText(_translate("Dialog", "Initial Time :"))
        self.label_6.setText(_translate("Dialog", "Update Speed (<1) :"))
        self.checkBox.setText(_translate("Dialog", "x"))
        self.checkBox_2.setText(_translate("Dialog", "y"))
        self.checkBox_3.setText(_translate("Dialog", "z"))
        self.label_7.setText(_translate("Dialog", "Time Data"))
        self.label_8.setText(_translate("Dialog", "Cartesian Preview Select"))
        self.pushButton.setText(_translate("Dialog", "Launch Program"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
